In [1]:
# QUES 1
import numpy as np

arr1 = np.array([10, 20])
arr2 = np.array([[30, 40],
                 [50, 60]])
print("1D Array:")
print(arr1)
print("\n2D Array:")
print(arr2)

1D Array:
[10 20]

2D Array:
[[30 40]
 [50 60]]


In [2]:
arr1_2d = arr1.reshape(1, 2)
print("1D Array reshaped to 2D:")
print(arr1_2d)

combined_arr = np.vstack((arr1_2d, arr2))
print("\nCombined Array:")
print(combined_arr)

1D Array reshaped to 2D:
[[10 20]]

Combined Array:
[[10 20]
 [30 40]
 [50 60]]


In [3]:
# QUES 2
arr=np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
array = arr.flatten()
print("Flattened 1D Array:")
print(array)

Flattened 1D Array:
[1 2 3 4 5 6 7 8 9]


In [5]:
# QUES 3
arr = np.array([10, 20, 30,40, 50, 60])
print("Original Array:")
print(arr)

reverse_arr = arr[::-1]
print("\nReversed Array:")
print(reverse_arr)

Original Array:
[10 20 30 40 50 60]

Reversed Array:
[60 50 40 30 20 10]


In [8]:
arr = np.array([[10, 20, 30],[40, 50, 60]])
print("Original Array:")
print(arr)

reverse_arr = arr[ ::-1, ::-1]
print("\nReversed Array:")
print(reverse_arr)

Original Array:
[[10 20 30]
 [40 50 60]]

Reversed Array:
[[60 50 40]
 [30 20 10]]


In [10]:
# QUES 4
print("Maximum Value:", np.max(arr))
print("Minimum Value:", np.min(arr))

rows, cols = arr.shape
print("\nNumber of Rows:", rows)
print("Number of Columns:", cols)

print("\nAll Elements:")
print(arr)
print("\nSpecific Element (Row 2, Column 3):")
print(arr[1][2])

Maximum Value: 60
Minimum Value: 10

Number of Rows: 2
Number of Columns: 3

All Elements:
[[10 20 30]
 [40 50 60]]

Specific Element (Row 2, Column 3):
60


In [11]:
total = 0
for row in arr:
    for element in row:
        total += element
print("Sum of All Elements:", total)

Sum of All Elements: 210


In [12]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])
print("First Array:", arr1)
print("Second Array:", arr2)

print("\nAddition:")
print(np.add(arr1, arr2))

print("\nSubtraction:")
print(np.subtract(arr1, arr2))

print("\nMultiplication:")
print(np.multiply(arr1, arr2))

print("\nDivision:")
print(np.divide(arr1, arr2))

First Array: [10 20 30]
Second Array: [1 2 3]

Addition:
[11 22 33]

Subtraction:
[ 9 18 27]

Multiplication:
[10 40 90]

Division:
[10. 10. 10.]


In [13]:
# QUES 5
arr3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("3D Array:")
print(arr3d)

# Using for loop
print("\nIterating using for loop:")
for block in arr3d:
    for row in block:
        for element in row:
            print(element)

# Using nditer
print("\nIterating using nditer:")
for element in np.nditer(arr3d):
    print(element)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Iterating using for loop:
1
2
3
4
5
6
7
8

Iterating using nditer:
1
2
3
4
5
6
7
8


In [14]:
# QUES 6
arr1 = np.array([3, 4]) 
arr2 = np.array([1, 0])
print("First Array:", arr1)
print("Second Array:", arr2)

avg = (arr1 + arr2) / 2
print("\nAverage of Arrays:")
print(avg)

First Array: [3 4]
Second Array: [1 0]

Average of Arrays:
[2. 2.]


In [15]:
arr1 = np.array([[10, 20],
                 [30, 40]])
arr2 = np.array([[50, 60],
                 [70, 80]])
print("First 2D Array:")
print(arr1)
print("\nSecond 2D Array:")
print(arr2)

avg = (arr1 + arr2) / 2
print("\nAverage of Arrays:")
print(avg)

First 2D Array:
[[10 20]
 [30 40]]

Second 2D Array:
[[50 60]
 [70 80]]

Average of Arrays:
[[30. 40.]
 [50. 60.]]


In [16]:
from statistics import mode
combined = np.concatenate((arr1, arr2))

print("Mean:", np.mean(combined))
print("Median:", np.median(combined))
print("Mode:", mode(combined.flatten()))

Mean: 45.0
Median: 45.0
Mode: 10
