In [1]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5, 6])
print("1D Array:")
print(arr1)

arr2 = arr1.reshape(2, 3)
print("\n2D Array:")
print(arr2)

1D Array:
[1 2 3 4 5 6]

2D Array:
[[1 2 3]
 [4 5 6]]


In [2]:
print("Array Attributes:")

print("Shape      :", arr2.shape)
print("Dimension  :", arr2.ndim)
print("Data Type  :", arr2.dtype)
print("Item Size  :", arr2.itemsize, "bytes")

Array Attributes:
Shape      : (2, 3)
Dimension  : 2
Data Type  : int64
Item Size  : 8 bytes


In [3]:
arr3 = np.full((3, 3), 9)
print("3×3 Array of all 9s:")
print(arr3) 

3×3 Array of all 9s:
[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [4]:
arr1 = np.linspace(25, 125, 10)
print("10 Evenly Spaced Values:")
print(arr1)

10 Evenly Spaced Values:
[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [5]:
my_list = [10, 20, 30, 40, 50]
arr2 = np.array(my_list)
print("NumPy Array from Python List:")
print(arr2)

NumPy Array from Python List:
[10 20 30 40 50]


In [6]:
reverse_arr = arr2[::-1]
print("Reversed Array:")
print(reverse_arr)

Reversed Array:
[50 40 30 20 10]


In [7]:
arr3 = np.arange(48).reshape(4, 4, 3)
print("4×4×3 Array:")
print(arr3)

value = arr3[1, 0, -1]
print("\nSecond Set, First Row, Last Column Value:")
print(value)


4×4×3 Array:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]

Second Set, First Row, Last Column Value:
14


In [8]:
arr4 = np.arange(1, 17).reshape(4, 4)
print("4×4 Array:")
print(arr4)

result = arr4[::2, 1::2]
print("\nOdd Rows and Even Columns:")
print(result)

4×4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Odd Rows and Even Columns:
[[ 2  4]
 [10 12]]


In [9]:
arr = np.arange(48).reshape(4, 4, 3)
print("4×4×3 Array:")
print(arr)

result = arr[1, :2, :2]
print("\nFirst 2 Rows and First 2 Columns of Second Set:")
print(result)

4×4×3 Array:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]

First 2 Rows and First 2 Columns of Second Set:
[[12 13]
 [15 16]]


In [ ]:
arr2 = np.array([[23, 56, 78, 93],
                 [71, 82, 13, 24]])
print("Original Array:")
print(arr2)

for i in range(arr2.shape[0]): 
    for j in range(arr2.shape[1]):
        if arr2[i][j] % 2 != 0:
            arr2[i][j] = -1

print("\nArray after replacing odd numbers with -1:")
print(arr2)

Original Array:
[[23 56 78 93]
 [71 82 13 24]]

Array after replacing odd numbers with -1:
[[-1 56 78 -1]
 [-1 82 -1 24]]


In [11]:
arr3 = np.array([1, 0, 2, 0, 3, 0, 4])
indices = np.nonzero(arr3)
print("Indices of Non-Zero Elements:")
print(indices)

Indices of Non-Zero Elements:
(array([0, 2, 4, 6]),)


In [12]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print("Array A:", a)
print("Array B:", b)

print("\nAddition:")
print(np.add(a, b))

print("\nMultiplication:")
print(np.multiply(a, b))

Array A: [10 20 30]
Array B: [1 2 3]

Addition:
[11 22 33]

Multiplication:
[10 40 90]


In [13]:
arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

dot_product = np.dot(arr1, arr2)
print("Dot Product:")
print(dot_product)

Dot Product:
1875
