In [ ]:
# QUES 1
import numpy as np
arr = np.array([
    [6, -8, 73, -110],
    [np.nan, -8, 0, 94]
])
print("Original Array:")
print(arr)

Original Array:
[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]


In [2]:
arr[np.isnan(arr)] = 0
print("\nArray after replacing NaN with 0:")
print(arr)


Array after replacing NaN with 0:
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]


In [3]:
transpose_arr = arr.T
print("\nArray after interchanging rows and columns:")
print(transpose_arr)


Array after interchanging rows and columns:
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [4]:
print("\nFirst 3 Rows and 3 Columns:")
print(transpose_arr[:3, :3])


First 3 Rows and 3 Columns:
[[ 6.  0.]
 [-8. -8.]
 [73.  0.]]


In [5]:
# QUES 2
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Original 3D Array:")
print(arr)

print("\nShape of Original Array:")
print(arr.shape)

Original 3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Shape of Original Array:
(2, 2, 2)


In [ ]:
# Move axis 0 to position 2
new_arr = np.moveaxis(arr, 0, 2)
print("\nArray after Moving Axes:")
print(new_arr)

print("\nShape after Moving Axes:")
print(new_arr.shape)


Array after Moving Axes:
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]

Shape after Moving Axes:
(2, 2, 2)


In [8]:
# QUES 3
import pandas as pd
data = {
    "Math": [90, 80, np.nan, 70],
    "Science": [85, np.nan, 75, 95]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

df = df.fillna(df.mean())
print("\nDataFrame after replacing NaN with column average:")
print(df)

Original DataFrame:
   Math  Science
0  90.0     85.0
1  80.0      NaN
2   NaN     75.0
3  70.0     95.0

DataFrame after replacing NaN with column average:
   Math  Science
0  90.0     85.0
1  80.0     85.0
2  80.0     75.0
3  70.0     95.0


In [10]:
# QUES 4
arr = np.array([10, -5, 20, -8, 15, -2])

print("Original Array:")
print(arr)

# Replace negative values with 0
arr[arr < 0] = 0

print("\nArray after replacing negative values with 0:")
print(arr)

# Replace negative values with 0
arr = np.where(arr < 0, 0, arr)

print("\nArray after replacement:")
print(arr)

Original Array:
[10 -5 20 -8 15 -2]

Array after replacing negative values with 0:
[10  0 20  0 15  0]

Array after replacement:
[10  0 20  0 15  0]
